[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
serde = {version = "1.0", features = ["derive"]}
risc0-zkvm = { version = "=0.19.1" }
num-bigint-dig = "0.8.4"